[package]
name = "eliza-modality-chat"
version.workspace = true
edition = "2024"
license.workspace = true
publish = false

[dependencies]
base64 = "0.22.1"
eliza-mad = { path = "../eliza-mad" }
eliza-modality-image = { path = "../modality-image" }
miette = { version = "7.6.0", features = ["derive"] }
schemars = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"

[lints]
workspace = true
