[package]
name = "eliza-modality-chat"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
bon = "=3.9.3"
eliza-mad = { path = "../eliza-mad" }
miette = { version = "7.6.0", features = ["derive"] }
schemars = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"

[lints]
workspace = true
