[package]
name = "eliza-server"
version.workspace = true
edition = "2024"
license.workspace = true
publish = false

[dependencies]
aide = { version = "0.15.1", features = ["axum", "scalar"] }
axum = "0.8.9"
eliza-http = { path = "../http" }
eliza-modality-speech = { path = "../modality-speech" }
eliza-server-anthropic = { path = "../server-anthropic" }
eliza-server-gemini = { path = "../server-gemini" }
eliza-server-ollama = { path = "../server-ollama" }
eliza-server-openai = { path = "../server-openai" }
miette = { version = "7.6.0", features = ["derive"] }
schemars = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["net"] }
tower-http = { version = "0.7.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[lints]
workspace = true
